/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "I2C.h"
#include "LCD.h"
#include "string.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[20];

	    I2CInit();
	    DelayMs(100);

	   LcdInit(SLOT_1);
	   DelayMs(100);
	   LcdPuts(SLOT_1, LCD_LINE1, "LCD1 OK yes");
	   DelayMs(100);

	    LcdInit(SLOT_2);
	    DelayMs(20);
	    LcdPuts(SLOT_2, LCD_LINE1, "LCD2 OK  yes");

	    LcdInit(MAIN);
	      	    DelayMs(100);
	      	    LcdPuts(MAIN, LCD_LINE1, "MAIN_LCD OK!");
	      	    LcdPuts(MAIN, LCD_LINE2, "Tested");

	    while(1)
	    {
	    	for(int i =0 ; i<1000;i++)
	    	{
	    		sprintf(str,"i is %d",i);
	    		LcdPuts(SLOT_1,LCD_LINE1, str);
	    		DelayMs(50);
	    		LcdPuts(SLOT_2,LCD_LINE2, str);
	    	    DelayMs(50);

	    	}
	    }



}

